#!/usr/bin/env node

'use strict';

const fs = require('fs');

if (process.env.MONGO_URI && !fs.existsSync('config.json')) {
  fs.writeFileSync('config.json', JSON.stringify({
    url: process.env.NODEBB_URL,
    mongo: { uri: process.env.MONGO_URI },
  }));
}

require('./src/cli');
